// "use client"
import Styles from './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import Link from 'next/link'
import { Controls } from './Controls';
// import { useState } from 'react';



export const metadata = {
  title: "Web Tutorials",
  description: "Generated by Green",
};
export default async function RootLayout({ children }) {
  console.log('공통레이아웃 작동');

  // const [topics, setTopics] = useState([]);
  // useEffect(() => {
  //   fetch('http://localhost:9999/topics/')
  //     .then(res => res.json())
  //     .then(result => {
  //       setTopics(result);
  //     })
  // }, []);
  // console.log(topics);

  const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}topics/`, {
    cache: 'no-store'
  });
  const topics = await res.json();

  return (
    <html lang="en">
      <body>
        <nav className='navbar bg-light'>
          <div className="container">
            <Link href="/" className="navbar-brand">Navbar</Link>
            <ul className="nav">
              {
                topics.map(item => {
                  console.log(item);
                  return <li key={item.id} className="nav-item"><Link href={`/read/${item.id}`} className="nav-link active">{item.title}</Link></li>;
                })
              }
              {/* <li className="nav-item">
                <Link href="/read/1" className="nav-link active">HTML</Link>
              </li>
              <li className="nav-item">
                <Link href="/read/2" className="nav-link active">CSS</Link>
              </li>
              <li className="nav-item">
                <Link href="/read/3" className="nav-link active">Javascript</Link>
              </li> */}
            </ul>
          </div>
        </nav>

        <main className='container my-3'>
          {children}
          <hr />
              <Controls></Controls>
        </main>
      </body>
    </html>
  );
}
